### ISSUE TITLE
Support for fabricjs version 1.7

### ISSUE THREAD

**Issue by davidderoo** [altert/OpenseadragonFabricjsOverlay#10]
Hi, do you guys have an idea when you will support fabricjs 1.7.
I get the following error with the demo:
fabric.js:1099 Uncaught TypeError: Cannot read property 'object' of undefined(…)(anonymous function) @ fabric.js:1099(anonymous function) @ fabric.js:2497
openseadragon-fabricjs-overlay.js:49 Uncaught TypeError: fabric.Canvas is not a constructor(…)Overlay @ openseadragon-fabricjs-overlay.js:49OpenSeadragon.Viewer.fabricjsOverlay @ openseadragon-fabricjs-overlay.js:15init @ demo.html:58(anonymous function) @ demo.html:173j @ jquery-1.11.2.min.js:2fireWith @ jquery-1.11.2.min.js:2ready @ jquery-1.11.2.min.js:2J @ jquery-1.11.2.min.js:2
I need this version because there is a problem in 1.5 with export to json and import to json.
Thank you very much.

David

**Comment by jetic83** [comment]
Yes, it does not seem to be compatible with the newest fabric.js 1.7.+. Would appreciate compatibility!!!

**Comment by altert** [comment]
can you reproduce it with fabric 1.7.3? demo seems to work for me without errors

**Comment by jetic83** [comment]
The demo today does not work for me in Windows 7 Chrome 55.0.2883.87 m (64-bit) and IE 11.0.96000 : Both the same problem: I can't drag and drop the objects. It will show the drag and drop cursor, but it will move the whole openseadragon image instead of the red or green objects. Also, I cannot click the "start drawing" button (it will just zoom into the image). 
Other than this, there is no java script error message in the Demo. Also in my application, I could now include fabrics.js 1.7.3 without problems! Thank you!

**Comment by altert** [comment]
Yes, it seems mouse:down event is at least partially broken since chrome 55. I don't have solution yet

**Comment by mohammedkhalilia** [comment]
I had it working few months ago with fabric 1.5. I also tried to go back and use the older version of fabric (1.5) but it is still not working. I am experiencing the same problem described by @jetic83

**Comment by mohammedkhalilia** [comment]
The following two lines will solve the issue you have with Chrome:

viewer.setControlsEnabled(false);
viewer.setMouseNavEnabled(false);

**Comment by altert** [comment]
see #11 for chrome 55+ discussion and workarounds
